version: "3.8"

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
