name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Create app directory
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
            mkdir -p /root/app
          '

      - name: Copy files to VPS
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude '.env' \
            --exclude '.nuxt' \
            --exclude '.output' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/app/

      - name: Create env file
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cat > /root/app/.env << 'EOL'
          BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
          TURSO_DATABASE_URL=${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }}
          NUXT_PUBLIC_SITE_URL=${{ secrets.NUXT_PUBLIC_SITE_URL }}
          NODE_ENV=production
          EOL"

      - name: Deploy with Docker
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /root/app && \
            docker compose pull && \
            docker compose down --remove-orphans && \
            docker compose build --no-cache && \
            docker compose up -d && \
            docker system prune -af"

      - name: Health check
        run: |
          echo "Waiting for application to start..."
          sleep 30
          curl --fail http://${{ secrets.VPS_HOST }}/api/health || exit 1
